apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Find-the-precious-Integration-1
  annotations:
    github.com/project-slug: eguezel/Find-the-precious-Integration-1
spec:
  type: other
  lifecycle: unknown
  owner: team-a
